---
name: Validate Pull Request Changes

on:
  pull_request:
    branches:
      - main
    paths:
      - eks/**

jobs:
  validate:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #required for oidc auth
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Setup TFenv
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.2
      
      - name: Install tgenv
        run: |
          git clone https://github.com/tgenv/tgenv.git ~/.tgenv
          echo "$HOME/.tgenv/bin" >> $GITHUB_PATH
      
      - name: Verify tgenv
        run: tgenv --version

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::138775093046:role/skillupwithsachin-gha-terraform-svc-role
          aws-region: us-east-1

      - name: Run Terragrunt Plan
        working-directory: environments/dev/skillupwithsachin-eks-demo
        run: |
          tgenv install
          tgenv use
          terragrunt init
          terragrunt plan --terragrunt-non-interactive
      
      - name: Cleanup
        run: |
          rm -rf .terraform .terragrunt-cache
      
